### ISSUE TITLE
Cannot save pngs

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mslice#337]
I have a window with a 2D plot. I click on the `Save Image` button, then select png extension, and I try to save the plot. I get 
```
Traceback (most recent call last):
  File "/home/3y9/Mantid/mslice/mslice/plotting/plot_window/plot_figure_manager.py", line 147, in save_plot
    save_workspaces([workspace], file_path, save_name, ext, slice_nonpsd=True)
  File "/home/3y9/Mantid/mslice/mslice/models/workspacemanager/workspace_algorithms.py", line 224, in save_workspaces
    raise RuntimeError("unrecognised file extension")
RuntimeError: unrecognised file extension

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/3y9/Mantid/mslice/mslice/plotting/plot_window/plot_figure_manager.py", line 149, in save_plot
    if e.message == "unrecognised file extension":
AttributeError: 'RuntimeError' object has no attribute 'message'
```

**Comment by martyngigg** [comment]
Thanks. @MatthewBowles can you take a look?
