### ISSUE TITLE
Crash when setting axes to log scale 

### ISSUE THREAD

**Issue by SilkeSchomann** [mantidproject/mslice#731]
**Describe the bug**
When setting axes to log scale MSlice crashed. For instance, when changing the scale setting in the plot options for a cut plot the following error message was displayed on Windows (MSlice as interface of Mantid nightly executable):
`Traceback (most recent call last):
 File "C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\presenters\plot_options_presenter.py", line 97, in get_new_config
 self._model.change_axis_scale(self._xy_config)
 File "C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\plotting\plot_window\cut_plot.py", line 176, in change_axis_scale
 min = get_min(ydata, absolute_minimum=0.)
 File "C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\plotting\plot_window\cut_plot.py", line 29, in get_min
 mask = np.greater(data, absolute_minimum)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

When changing the scale by double-clicking on the y-axis the error message was different:
`Traceback (most recent call last):
  File "C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\presenters\quick_options_presenter.py", line 30, in <lambda>
    view.ok_clicked.connect(lambda: _set_axis_options(view, target, model, has_logarithmic, grid))
  File "C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\presenters\quick_options_presenter.py", line 51, in _set_axis_options
    setattr(model, target[:-5] + 'log', view.log_scale.isChecked())
  File "C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\plotting\plot_window\cut_plot.py", line 457, in y_log
    self.change_axis_scale(config)
  File "C:\MantidNightlyInstall\scripts\ExternalInterfaces\mslice\plotting\plot_window\cut_plot.py", line 178, in change_axis_scale
    current_axis.set_yscale('symlog', linthreshy=pow(10, np.floor(np.log10(min))))
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\axes\_base.py", line 4117, in set_yscale
    ax.yaxis._set_scale(value, **kwargs)
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\axis.py", line 761, in _set_scale
    self._scale = mscale.scale_factory(value, self, **kwargs)
  File "C:\MantidNightlyInstall\bin\lib\site-packages\matplotlib\scale.py", line 597, in scale_factory
    return scale_cls(axis, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'linthreshy'`

Setting a negative value on the colour bar axis and changing to a log scale caused the following error message:
`Traceback (most recent call last):
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\cbook\__init__.py", line 287, in process
    func(*args, **kwargs)
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\colorbar.py", line 551, in update_normal
    self.draw_all()
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\colorbar.py", line 578, in draw_all
    self._process_values()
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\colorbar.py", line 1144, in _process_values
    b = self.norm.inverse(b)
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\colors.py", line 1554, in inverse
    raise ValueError("Invalid vmin or vmax")
ValueError: Invalid vmin or vmax
Traceback (most recent call last):
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\cbook\__init__.py", line 287, in process
    func(*args, **kwargs)
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\colorbar.py", line 551, in update_normal
    self.draw_all()
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\colorbar.py", line 578, in draw_all
    self._process_values()
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\colorbar.py", line 1144, in _process_values
    b = self.norm.inverse(b)
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\colors.py", line 1554, in inverse
    raise ValueError("Invalid vmin or vmax")
ValueError: Invalid vmin or vmax
Traceback (most recent call last):
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\cbook\__init__.py", line 287, in process
    func(*args, **kwargs)
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\colorbar.py", line 551, in update_normal
    self.draw_all()
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\colorbar.py", line 578, in draw_all
    self._process_values()
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\colorbar.py", line 1144, in _process_values
    b = self.norm.inverse(b)
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\colors.py", line 1554, in inverse
    raise ValueError("Invalid vmin or vmax")
ValueError: Invalid vmin or vmax
Traceback (most recent call last):
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\cbook\__init__.py", line 287, in process
    func(*args, **kwargs)
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\colorbar.py", line 551, in update_normal
    self.draw_all()
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\colorbar.py", line 578, in draw_all
    self._process_values()
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\colorbar.py", line 1144, in _process_values
    b = self.norm.inverse(b)
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\colors.py", line 1554, in inverse
    raise ValueError("Invalid vmin or vmax")
ValueError: Invalid vmin or vmax
Traceback (most recent call last):
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\mslice\presenters\quick_options_presenter.py", line 30, in <lambda>
    view.ok_clicked.connect(lambda: _set_axis_options(view, target, model, has_logarithmic, grid))
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\mslice\presenters\quick_options_presenter.py", line 51, in _set_axis_options
    setattr(model, target[:-5] + 'log', view.log_scale.isChecked())
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\mslice\plotting\plot_window\slice_plot.py", line 464, in colorbar_log
    self.change_axis_scale(self.colorbar_range, value)
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\mslice\plotting\plot_window\slice_plot.py", line 216, in change_axis_scale
    self._canvas.figure.colorbar(colormesh)
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\figure.py", line 1210, in colorbar
    cb = cbar.Colorbar(cax, mappable, **cb_kw)
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\colorbar.py", line 483, in __init__
    self._reset_locator_formatter_scale()
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\colorbar.py", line 1206, in _reset_locator_formatter_scale
    self._process_values()
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\colorbar.py", line 1144, in _process_values
    b = self.norm.inverse(b)
  File "C:\Users\dsc49661\AppData\Local\mambaforge\envs\mslice_new\lib\site-packages\matplotlib\colors.py", line 1554, in inverse
    raise ValueError("Invalid vmin or vmax")
ValueError: Invalid vmin or vmax`

**Additional context**
This problem occurs in Mantid as well (https://github.com/mantidproject/mantid/issues/33910) and might be caused by the matplotlib update.

**Comment by MialLewis** [comment]
I can't replicate this on release text, either build as an unstable package or run via VS. I have tried both debug and release builds.
