### ISSUE TITLE
GDOS Intensity correction causes an unhandled error with pixel workspaces on cuts

### ISSUE THREAD

**Issue by MialLewis** [mantidproject/mslice#826]
**Describe the bug**
GDOS Intensity correction causes an unhandled error with pixel workspaces on cuts

**To Reproduce**
1.  Load a pixel dataset into mslice (`HYS_63363_4pixel` used).
2. `Calculate project` with default settings
3. On `Cut` tab, plot a cut along `DeltaE` from -0.5 to 0.5, from 1.7 to 2
4. Change intensity to `GDOS` via `intensity` drop down, input temperature (`110` used).

**Expected behavior**
No error, correction applied.

**Stack Trace**
```
Traceback (most recent call last):
  File "C:\Repos\GitHub\conda\mslice\mslice\plotting\plot_window\cut_plot.py", line 602, in _run_temp_dependent
    cut_plotter_method(self._canvas.figure.axes[0])
  File "C:\Repos\GitHub\conda\mslice\mslice\presenters\cut_plotter_presenter.py", line 272, in show_gdos
    self._show_intensity(self._cut_cache_dict[axes], IntensityType.GDOS)
  File "C:\Repos\GitHub\conda\mslice\mslice\presenters\cut_plotter_presenter.py", line 252, in _show_intensity
    self._plot_cut(workspace, cached_cut, plot_over=plot_over, intensity_correction=intensity_correction)
  File "C:\Repos\GitHub\conda\mslice\mslice\presenters\cut_plotter_presenter.py", line 56, in _plot_cut
    cut_ws = cut.get_intensity_corrected_ws(intensity_correction)
  File "C:\Repos\GitHub\conda\mslice\mslice\models\cut\cut.py", line 209, in get_intensity_corrected_ws
    return self.gdos
  File "C:\Repos\GitHub\conda\mslice\mslice\models\cut\cut.py", line 191, in gdos
    self._gdos = cut_compute_gdos(self._cut_ws, self.sample_temp, self.q_axis, self.e_axis, self.rotated,
  File "C:\Repos\GitHub\conda\mslice\mslice\models\cut\cut.py", line 147, in sample_temp
    raise SampleTempValueError('sample temperature not found', self.workspace_name)
mslice.models.cut.cut.SampleTempValueError: ('sample temperature not found', 'HYS_63373_4pixel_QE_cut(1.700,2.000)')
```

**Comment by MialLewis** [comment]
For record:

The GDOS intensity correction workflow for cuts is the following:
- Fetch original slice
- Correct original slice for GDOS (including binary ops)
- Take cut from the corrected slice

For pixel workspaces the binary op functionality results in a MDHisto workspace which is then rewrapped as a pixel workspace. This effectively removes the raw_ws (which is not transformed by the binary op).

You cannot therefore pass the resulting pixel workspace into the cut algorithm as there is no associated raw workspace. In passing the MDHisto workspace instead a warning is regarding axis aligned binning.
