### ISSUE TITLE
Workspace name containing a ')' causes problems

### ISSUE THREAD

**Issue by SilkeSchomann** [mantidproject/mslice#934]
**Describe the bug**
Renaming a workspace to a name containing a closing bracket (')') causes this workspace to function. Renaming this workspace again does not solve the problem.

This could be a Mantid-wide issue.

**Comment by robertapplin** [comment]
```
Traceback (most recent call last):
  File "C:\Users\mlc47243\Documents\mantid-dev\mslice\src\mslice\widgets\slice\slice.py", line 52, in _btn_clicked
    self._presenter.notify(Command.DisplaySlice)
  File "C:\Users\mlc47243\Documents\mantid-dev\mslice\src\mslice\presenters\slice_widget_presenter.py", line 41, in notify
    self._display_slice()
  File "C:\Users\mlc47243\Documents\mantid-dev\mslice\src\mslice\presenters\slice_widget_presenter.py", line 62, in _display_slice
    self._plot_slice(selected_workspace, x_axis, y_axis, intensity_start, intensity_end,
  File "C:\Users\mlc47243\Documents\mantid-dev\mslice\src\mslice\presenters\slice_widget_presenter.py", line 67, in _plot_slice
    self._slice_plotter_presenter.plot_slice(*args)
  File "C:\Users\mlc47243\Documents\mantid-dev\mslice\src\mslice\presenters\slice_plotter_presenter.py", line 25, in plot_slice
    self.create_slice(workspace, x_axis, y_axis, intensity_start, intensity_end, norm_to_one, colourmap)
  File "C:\Users\mlc47243\Documents\mantid-dev\mslice\src\mslice\presenters\slice_plotter_presenter.py", line 30, in create_slice
    slice = compute_slice(selected_ws, x_axis, y_axis, norm_to_one)
  File "C:\Users\mlc47243\Documents\mantid-dev\mslice\src\mslice\models\slice\slice_functions.py", line 18, in compute_slice
    slice = mantid_algorithms.Slice(OutputWorkspace='__' + workspace.name, InputWorkspace=workspace,
  File "C:\Users\mlc47243\Documents\mantid-dev\mslice\src\mslice\util\mantid\algorithm_wrapper.py", line 67, in alg_wrapper
    result.name = output_name
  File "C:\Users\mlc47243\Documents\mantid-dev\mslice\src\mslice\workspace\workspace.py", line 34, in name
    rename_workspace(raw_name, re.sub(rf"{self.name}\w*", new_name, raw_name))
  File "C:\Users\mlc47243\AppData\Local\mambaforge\envs\mantidnightly\lib\re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Users\mlc47243\AppData\Local\mambaforge\envs\mantidnightly\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\mlc47243\AppData\Local\mambaforge\envs\mantidnightly\lib\sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\mlc47243\AppData\Local\mambaforge\envs\mantidnightly\lib\sre_parse.py", line 969, in parse
    raise source.error("unbalanced parenthesis")
```

**Comment by SilkeSchomann** [comment]
@robertapplin Yes, that is the error message we got as well on different OS.
